services:
  backend:
    build:
      context: ./backend/nailsbymandy/  # Path to the Django backend directory
      dockerfile: Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/nailsbymandy  # Sync project files for development
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

  # frontend:
  #   build:
  #     context: ./frontend/  # Path to the React frontend directory
  #     dockerfile: Dockerfile
  #   container_name: react-frontend
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
