# Generated by Django 5.1.1 on 2024-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='home_phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
