# Generated by Django 5.1.1 on 2024-09-15 11:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_description', models.CharField(max_length=600)),
                ('service_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/service_images/')),
                ('waxing', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_booking', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_off', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('review_description', models.CharField(max_length=600)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_posted', models.DateField()),
                ('display_review', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_posting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_timestamp', models.DateField(default=datetime.datetime.now)),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid', models.BooleanField()),
                ('discount', models.IntegerField()),
                ('discont_details', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='bookings.services')),
            ],
        ),
    ]
