# Generated by Django 5.1.1 on 2024-09-15 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
