# Generated by Django 5.1.1 on 2024-09-20 09:51

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_updated_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now(), null=None, blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
