# Generated by Django 5.1.1 on 2024-09-22 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_booking_updated_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_updated_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
